/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaFundamentals;

public class App {
    public static String pluralize(String word, int number) {
        if (number > 1) {
            return "I own" + " " + number + " " + word + "s";
        } else {
            return "I own" + " " + number + " " + word;
        }
    }

    public static String flipNHeads(int n) {
        int consecutiveHeadFlips = 0;
        int flips = 0;
        while(consecutiveHeadFlips !=n) {
            double random = Math.random();
            if (random < .5) {
                System.out.println("TAILS");
                consecutiveHeadFlips = 0;
                flips++;
            }
            if (random >=.5) {
                System.out.println("HEADS");
                consecutiveHeadFlips++;
                flips++;
            }
        }
        return "It took " + flips + " flips to get " + n + " heads in a row.";
    }

    public static void main(String[] args) {
        System.out.println(pluralize("cat", 4));
        System.out.println(flipNHeads(4));
    }
}
